
export const METU_DEPARTMENTS = [
  "İngilizce Hazırlık Programı",
  "Bilgisayar Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Makina Mühendisliği",
  "İnşaat Mühendisliği",
  "Endüstri Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Kimya Mühendisliği",
  "Çevre Mühendisliği",
  "Gıda Mühendisliği",
  "Jeoloji Mühendisliği",
  "Maden Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Petrol ve Doğalgaz Mühendisliği",
  "Mimarlık",
  "Şehir ve Bölge Planlama",
  "Endüstriyel Tasarım",
  "Psikoloji",
  "Sosyoloji",
  "Felsefe",
  "Tarih",
  "İktisat",
  "İşletme",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Uluslararası İlişkiler",
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "İstatistik",
  "Moleküler Biyoloji ve Genetik",
  "İngilizce Öğretmenliği",
  "Okul Öncesi Eğitimi",
  "Bilgisayar ve Öğretim Teknolojileri Eğitimi",
  "Fen Bilgisi Öğretmenliği",
  "İlköğretim Matematik Öğretmenliği",
  "Beden Eğitimi ve Spor",
  "Diğer"
];
